name = "nl-kamado"
main = "worker.js"
workers_dev = true
compatibility_date = "2024-09-01"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "nl_kamado_db"
database_id = "7897664a-27ca-4d3a-a3ed-01f5a8a8edea"

# Cloudflare R2 Bucket binding
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "nl-kamado-assets"

# Cloudflare Service Binding to shared mail-sender
[[services]]
binding = "MAIL_SENDER"
service = "mail-sender"

[vars]
SITE_URL = "https://smokeykamado.nl"
APP_ENV = "production"
STORE_NAME = "SmokeyKamado Nederland"
CURRENCY = "EUR"
NOTIFY_EMAIL = "ferkomes@gmail.com"
