// Customer information for the current interest survey, not a live sales checkout.
const SUPPORT_PAGES = {
  '/support/shipping': {
    nl: ['Verzending & levering', `
      <h2>Geplande bezorgkosten</h2><p>Onderstaande bedragen zijn indicatief, inclusief btw, voor levering op het Nederlandse vasteland. Er is nog geen bindende bestelling of betaling mogelijk.</p>
      <table><tr><th>Product</th><th>Bezorging</th></tr><tr><td>18″ Basic / Premium, 21″ en 23″</td><td>€99 per kamado</td></tr><tr><td>27″ Premium</td><td>€129 per kamado</td></tr><tr><td>Alleen accessoires</td><td>€7,95 per bestelling</td></tr></table>
      <p>Accessoires die samen met een kamado worden verzonden, hebben geen extra bezorgkosten. Eilanden, andere landen en adressen met bijzondere toegangsbeperkingen: alleen op vooraf afgesproken offerte. De winkelwagen toont voor zulke adressen nog de vastelandindicatie.</p>
      <h2>Levering op afspraak, aan de stoeprand</h2><p>Een kamado wordt op een pallet vervoerd. Het geplande serviceniveau is aflevering met laadklep en palletwagen op een bereikbare, vlakke, verharde plek aan de openbare weg. Bezorgen over grind, trappen, door de woning of in de tuin, montage en het meenemen van verpakkingen zijn niet inbegrepen. Meld toegangsbeperkingen vooraf.</p>
      <h2>Beschikbaarheid en levertijd</h2><p>Deze website peilt belangstelling voor een toekomstige collectie. Er wordt nu niets verzonden. Vóór een eventuele aankoop ontvang je de werkelijke beschikbaarheid, verzendkosten en afgesproken levertermijn; er worden geen onverwachte toeslagen achteraf opgelegd.</p>
      <h2>Transportschade</h2><p>Bij een toekomstige consumentenkoop blijven wij verantwoordelijk voor het vervoer tot ontvangst door jou of een door jou aangewezen derde, tenzij je zelf een niet door ons aangeboden vervoerder kiest. Controleer de verpakking waar mogelijk en meld schade met foto's zo snel mogelijk. Het ontbreken van foto's of een aantekening bij de chauffeur neemt je wettelijke rechten niet weg. Een volledige allrisk-transportverzekering is nog niet bevestigd en wordt daarom niet beloofd.</p>`],
    en: ['Shipping & delivery', `
      <h2>Planned delivery charges</h2><p>These are estimates including VAT for mainland Netherlands. No binding order or payment is currently possible.</p>
      <table><tr><th>Product</th><th>Delivery</th></tr><tr><td>18″ Basic / Premium, 21″ and 23″</td><td>€99 per kamado</td></tr><tr><td>27″ Premium</td><td>€129 per kamado</td></tr><tr><td>Accessories only</td><td>€7.95 per order</td></tr></table>
      <p>Accessories shipped with a kamado incur no extra delivery charge. Islands, other countries and restricted-access addresses require an agreed quote. The basket currently shows the mainland estimate for these addresses too.</p>
      <h2>Scheduled kerbside delivery</h2><p>Kamados travel on a pallet. The planned service is delivery with a tail lift and pallet truck to an accessible, level, paved location beside the public road. Carrying over gravel, up steps, indoors or into a garden, assembly and packaging removal are not included. Tell us about access restrictions in advance.</p>
      <h2>Availability and delivery dates</h2><p>This website surveys interest in a future collection. Nothing ships at this stage. Actual availability, shipping charges and delivery dates will be confirmed before any purchase. No unexpected surcharges will be imposed afterwards.</p>
      <h2>Transport damage</h2><p>For a future consumer purchase, we remain responsible for transport until receipt by you or your designated third party, unless you independently choose a carrier we did not offer. Where possible, inspect the packaging and report damage with photographs promptly. Missing photographs or a note to the driver do not remove your statutory rights. Full all-risk transport insurance has not yet been confirmed and is not promised.</p>`]
  },
  '/support/warranty': {
    nl: ['Garantie & service', `
      <h2>Je wettelijke garantie</h2><p>Bij een consumentenkoop heb je recht op een product dat voldoet aan wat je redelijkerwijs mag verwachten, gelet op onder meer prijs, omschrijving en normaal gebruik. De wettelijke garantie heeft in Nederland geen vaste termijn van twee of vijf jaar.</p>
      <p>Voldoet het product niet aan de overeenkomst, dan zorgen wij volgens de wettelijke regels voor een kosteloze oplossing, doorgaans reparatie of vervanging binnen een redelijke termijn en zonder ernstige overlast. Ook noodzakelijke transportkosten zijn dan voor ons. Als de wettelijke voorwaarden daarvoor zijn vervuld, kun je prijsvermindering of ontbinding vragen.</p>
      <h2>Keramiek en onderdelen</h2><p>Een aanvullende levenslange garantie op keramiek of vijfjarige garantie op hardware is nog niet schriftelijk bevestigd. Wij bieden die aanvullende commerciële garantie daarom momenteel niet aan. Eventuele toekomstige fabrieksgarantie wordt vóór aankoop met de precieze dekking, looptijd, garantieverstrekker en procedure vermeld en beperkt nooit je wettelijke rechten.</p>
      <p>Normale slijtage of schade door onjuist gebruik is niet automatisch een productgebrek. Wij beoordelen elke melding op de oorzaak en omstandigheden; er geldt geen algemene uitsluiting voor alle keramiek, pakkingen of metalen onderdelen.</p>
      <h2>Een probleem melden</h2><p>Mail je naam, aankoopbewijs indien beschikbaar, model en een beschrijving naar <a href="mailto:info@smokeykamado.nl">info@smokeykamado.nl</a>. Foto's helpen bij de beoordeling. Organiseer bij een zware kamado bij voorkeur eerst samen met ons het transport. Dit overleg beperkt je wettelijke rechten niet.</p>`],
    en: ['Warranty & support', `
      <h2>Your statutory rights</h2><p>For a consumer purchase, your product must meet reasonable expectations based on its price, description and normal use. Dutch statutory conformity rights do not have a fixed two-year or five-year limit.</p>
      <p>If the product does not conform to the contract, we provide a remedy under the applicable rules, normally free repair or replacement within a reasonable time and without significant inconvenience. Necessary transport costs are ours. Where the legal conditions are met, you may request a price reduction or cancellation.</p>
      <h2>Ceramics and components</h2><p>An additional lifetime ceramics warranty or five-year hardware warranty has not been confirmed in writing. We therefore do not currently offer these commercial guarantees. Any future manufacturer guarantee will be described before purchase, including its coverage, duration, provider and claim procedure. It will never restrict your statutory rights.</p>
      <p>Normal wear or damage caused by misuse is not automatically a product defect. Claims are assessed individually by their cause and circumstances; we do not apply a blanket exclusion to ceramics, gaskets or metal parts.</p>
      <h2>Reporting a problem</h2><p>Email your name, proof of purchase if available, model and a description to <a href="mailto:info@smokeykamado.nl">info@smokeykamado.nl</a>. Photographs help us assess the issue. Please coordinate heavy-item transport with us where possible; this does not restrict your statutory rights.</p>`]
  },
  '/support/returns': {
    nl: ['Retourneren & herroepen', `
      <h2>Nu: vrijblijvend interesse melden</h2><p>Er is momenteel geen koopovereenkomst, betaling of levering. Je kunt je interesse zonder kosten intrekken door ons te mailen.</p>
      <h2>Gepland retourbeleid bij opening: 30 dagen</h2><p>Bij toekomstige consumentenverkopen bieden wij 30 dagen om zonder reden te herroepen, gerekend vanaf de dag na ontvangst van het product (bij een gesplitste bestelling na het laatste product). Dit verlengt de wettelijke bedenktijd van 14 dagen. Dezelfde onderstaande werkwijze geldt tijdens de volledige 30 dagen.</p>
      <p>Meld je herroeping binnen die termijn per e-mail. Een duidelijke verklaring is voldoende; ons voorbeeld hieronder is niet verplicht. Stuur het product binnen 14 dagen na je melding terug. Wij geven vóór verkoop het retouradres en instructies; stuur nu niets naar een onbevestigd adres.</p>
      <h2>Retourkosten en verpakking</h2><p>Bij herroeping betaal je de rechtstreekse retourkosten. Voor een kamado moet je voorlopig rekenen op circa €99–€179 inclusief btw voor pallettransport binnen het Nederlandse vasteland; dit is een planningsraming, geen vervoerdersofferte. Voor losse accessoires geldt het tarief van de gekozen pakketdienst. Vóór de verkoop worden de toepasselijke kosten en een raming voor niet-postale goederen duidelijk bevestigd. Bij een gegrond beroep op wettelijke garantie zijn noodzakelijke retourkosten voor ons.</p>
      <p>Verpak het product stevig en veilig; bewaar bij voorkeur pallet en beschermingsmateriaal. Originele verpakking is geen voorwaarde voor het herroepingsrecht. Je mag het product bekijken zoals in een winkel. Gebruik dat verder gaat dan nodig om aard, kenmerken en werking vast te stellen — bijvoorbeeld stoken of koken — kan tot waardevermindering leiden, maar sluit herroeping niet automatisch uit.</p>
      <h2>Terugbetaling</h2><p>Bij volledige herroeping betalen wij het aankoopbedrag en de standaard heenzendkosten terug binnen 14 dagen na je melding, via hetzelfde betaalmiddel tenzij anders afgesproken. Extra kosten van een duurdere bezorgoptie worden niet terugbetaald. Wij mogen wachten tot wij het product of bewijs van terugzending hebben ontvangen, afhankelijk van wat eerst komt. Er zijn geen standaard administratie- of herbevoorradingskosten.</p>
      <h2>Voorbeeldverklaring</h2><p>Aan: info@smokeykamado.nl<br>Hierbij herroep ik de overeenkomst voor: [product].<br>Besteld op / ontvangen op: [datum].<br>Naam en adres: [gegevens].<br>Bestelnummer indien bekend: [nummer].<br>Datum: [datum].<br>Handtekening: alleen bij een papieren verklaring.</p>`],
    en: ['Returns & withdrawal', `
      <h2>Now: non-binding interest registration</h2><p>There is currently no sales contract, payment or delivery. You can withdraw your interest free of charge by emailing us.</p>
      <h2>Planned policy at launch: 30 days</h2><p>For future consumer sales, we plan to allow 30 days to withdraw without a reason, starting the day after receipt (after the final item for a split order). This extends the statutory 14-day period. The procedure below applies throughout all 30 days.</p>
      <p>Notify us by email within this period. Any clear withdrawal statement is sufficient; the example below is optional. Return the goods within 14 days of notifying us. The return address and instructions will be supplied before sales begin; do not send goods to an unconfirmed address.</p>
      <h2>Return costs and packaging</h2><p>You pay direct return costs when withdrawing. For a kamado, budget approximately €99–€179 including VAT for mainland Netherlands pallet transport. This is a planning estimate, not a carrier quote. Accessories incur your chosen parcel carrier's rate. Applicable costs and an estimate for goods unsuitable for normal post will be clearly confirmed before sale. Necessary return costs for a valid statutory conformity claim are ours.</p>
      <p>Pack goods securely; retaining the pallet and protective materials is recommended. Original packaging is not a condition of withdrawal. You may inspect the product as in a shop. Handling beyond what is needed to establish its nature, characteristics and functioning — such as lighting a fire or cooking — may cause a deduction for diminished value, but does not automatically remove the right to withdraw.</p>
      <h2>Refunds</h2><p>For full withdrawal, we refund the purchase price and standard outbound delivery charge within 14 days of notification using the original payment method unless agreed otherwise. The extra cost of a premium delivery option is not refunded. We may wait until the goods or evidence of return are received, whichever occurs first. There is no standard administration or restocking fee.</p>
      <h2>Example withdrawal statement</h2><p>To: info@smokeykamado.nl<br>I withdraw from my contract for: [product].<br>Ordered on / received on: [date].<br>Name and address: [details].<br>Order reference if known: [reference].<br>Date: [date].<br>Signature: only for a paper statement.</p>`]
  }
};
function supportPageHtml(path, language) {
  const lang = language === 'en' ? 'en' : 'nl';
  const [title, body] = SUPPORT_PAGES[path][lang];
  const nav = Object.entries(SUPPORT_PAGES).map(([href, text]) => `<a href="${href}?lang=${lang}" ${href === path ? 'aria-current="page"' : ''}>${text[lang][0]}</a>`).join('');
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | SmokeyKamado</title><meta name="robots" content="noindex"><style>
  *{box-sizing:border-box}body{margin:0;background:#f5f3ed;color:#20392e;font:17px/1.7 system-ui,sans-serif}header,footer{background:#153b2c;color:#fff;padding:24px max(20px,calc((100% - 880px)/2))}header img{width:220px;max-width:100%}a{color:inherit;text-underline-offset:4px}nav{display:flex;flex-wrap:wrap;gap:12px 22px;margin-top:18px;font-size:15px}nav [aria-current]{font-weight:700}main{max-width:920px;margin:auto;padding:35px 20px 60px}h1{font-size:clamp(30px,5vw,44px);line-height:1.2}h2{font-size:23px;margin-top:32px;line-height:1.3}.notice{padding:16px 20px;border-left:4px solid #bc7845;background:#e9e5db}table{width:100%;border-collapse:collapse}td,th{padding:12px 8px;text-align:left;border-bottom:1px solid #ccc}footer{font-size:14px}a:focus-visible{outline:3px solid #bc7845;outline-offset:4px}
  </style></head><body><header><a href="/?lang=${lang}"><img src="/assets/smokey-logo.svg" alt="SmokeyKamado — home"></a><nav>${nav}<a href="${path}?lang=${lang === 'nl' ? 'en' : 'nl'}">${lang === 'nl' ? 'English' : 'Nederlands'}</a></nav></header><main><h1>${title}</h1><p class="notice">${lang === 'nl' ? 'SmokeyKamado is in voorbereiding. Deze website verzamelt vrijblijvende interesse; er worden geen bestellingen of betalingen aangenomen.' : 'SmokeyKamado is preparing to launch. This website collects non-binding interest; no orders or payments are accepted.'}</p>${body}<p><a href="mailto:info@smokeykamado.nl">info@smokeykamado.nl</a></p></main><footer>${lang === 'nl' ? 'Vóór verkoop publiceren wij de juridische verkopersgegevens, het vestigings- en retouradres, registratienummer en btw-gegevens. Deze informatiepagina is geen volledige set verkoopvoorwaarden.' : 'Before sales open, we will publish the legal seller details, business and return addresses, registration and VAT details. This information page is not a complete set of sales terms.'}</footer></body></html>`;
}
